/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package defencesystem.superdefence;

import java.awt.Color;

/**
 *
 * @author Nirodha
 */
public class SuperDefence extends javax.swing.JFrame {

    /**
     * Creates new form SuperDefence
     */
    public SuperDefence() {
        initComponents();
        setLocationRelativeTo(null);
        getContentPane().setBackground(new Color(247f / 255, 247f / 255, 242f / 255, 0.635f));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        jLabelAreaClearance = new javax.swing.JLabel();
        jCheckBoxPosition = new javax.swing.JCheckBox();
        jButtonShoot = new javax.swing.JButton();
        jButtonLaser = new javax.swing.JButton();
        jButtonMissile = new javax.swing.JButton();
        jLabelSoldierCount = new javax.swing.JLabel();
        jLabelAmmoCount = new javax.swing.JLabel();
        jSpinnerSoldier = new javax.swing.JSpinner();
        jSpinnerAmmo = new javax.swing.JSpinner();
        jScrollPaneDisplayArea = new javax.swing.JScrollPane();
        jTextPaneDisplayArea = new javax.swing.JTextPane();
        jScrollPaneInputArea = new javax.swing.JScrollPane();
        jTextAreaInput = new javax.swing.JTextArea();
        jButtonSend = new javax.swing.JButton();
        jSliderFuelAmount = new javax.swing.JSlider();

        setTitle("Super Defence");
        setPreferredSize(new java.awt.Dimension(800, 650));
        setResizable(false);

        jLabelAreaClearance.setBackground(new java.awt.Color(237, 111, 52));
        jLabelAreaClearance.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelAreaClearance.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAreaClearance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAreaClearance.setText("Area Not Cleared");
        jLabelAreaClearance.setMaximumSize(new java.awt.Dimension(250, 50));
        jLabelAreaClearance.setMinimumSize(new java.awt.Dimension(250, 50));
        jLabelAreaClearance.setOpaque(true);
        jLabelAreaClearance.setPreferredSize(new java.awt.Dimension(250, 50));

        jCheckBoxPosition.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jCheckBoxPosition.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBoxPosition.setText("Position");
        jCheckBoxPosition.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jCheckBoxPosition.setMaximumSize(new java.awt.Dimension(120, 40));
        jCheckBoxPosition.setMinimumSize(new java.awt.Dimension(120, 40));
        jCheckBoxPosition.setPreferredSize(new java.awt.Dimension(120, 40));

        jButtonShoot.setBackground(new java.awt.Color(129, 182, 183));
        jButtonShoot.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonShoot.setForeground(new java.awt.Color(0, 0, 0));
        jButtonShoot.setText("Shoot");
        jButtonShoot.setMaximumSize(new java.awt.Dimension(270, 50));
        jButtonShoot.setMinimumSize(new java.awt.Dimension(270, 50));
        jButtonShoot.setPreferredSize(new java.awt.Dimension(270, 50));
        jButtonShoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShootActionPerformed(evt);
            }
        });

        jButtonLaser.setBackground(new java.awt.Color(129, 182, 183));
        jButtonLaser.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonLaser.setForeground(new java.awt.Color(0, 0, 0));
        jButtonLaser.setText("Laser Operation");
        jButtonLaser.setMaximumSize(new java.awt.Dimension(270, 50));
        jButtonLaser.setMinimumSize(new java.awt.Dimension(270, 50));
        jButtonLaser.setPreferredSize(new java.awt.Dimension(270, 50));
        jButtonLaser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLaserActionPerformed(evt);
            }
        });

        jButtonMissile.setBackground(new java.awt.Color(129, 182, 183));
        jButtonMissile.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonMissile.setForeground(new java.awt.Color(0, 0, 0));
        jButtonMissile.setText("Missile Operation");
        jButtonMissile.setMaximumSize(new java.awt.Dimension(270, 50));
        jButtonMissile.setMinimumSize(new java.awt.Dimension(270, 50));
        jButtonMissile.setPreferredSize(new java.awt.Dimension(270, 50));
        jButtonMissile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMissileActionPerformed(evt);
            }
        });

        jLabelSoldierCount.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelSoldierCount.setForeground(new java.awt.Color(0, 0, 0));
        jLabelSoldierCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSoldierCount.setText("Soldier Count");
        jLabelSoldierCount.setMaximumSize(new java.awt.Dimension(140, 50));
        jLabelSoldierCount.setMinimumSize(new java.awt.Dimension(140, 50));
        jLabelSoldierCount.setPreferredSize(new java.awt.Dimension(140, 50));

        jLabelAmmoCount.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelAmmoCount.setForeground(new java.awt.Color(0, 0, 0));
        jLabelAmmoCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAmmoCount.setText("Ammo Count");
        jLabelAmmoCount.setMaximumSize(new java.awt.Dimension(140, 50));
        jLabelAmmoCount.setMinimumSize(new java.awt.Dimension(140, 50));
        jLabelAmmoCount.setPreferredSize(new java.awt.Dimension(140, 50));

        jSpinnerSoldier.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jSpinnerSoldier.setToolTipText("");
        jSpinnerSoldier.setMaximumSize(new java.awt.Dimension(80, 50));
        jSpinnerSoldier.setMinimumSize(new java.awt.Dimension(80, 50));
        jSpinnerSoldier.setPreferredSize(new java.awt.Dimension(80, 50));

        jSpinnerAmmo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jSpinnerAmmo.setToolTipText("");
        jSpinnerAmmo.setMaximumSize(new java.awt.Dimension(80, 50));
        jSpinnerAmmo.setMinimumSize(new java.awt.Dimension(80, 50));
        jSpinnerAmmo.setPreferredSize(new java.awt.Dimension(80, 50));

        jScrollPaneDisplayArea.setMaximumSize(new java.awt.Dimension(570, 180));
        jScrollPaneDisplayArea.setMinimumSize(new java.awt.Dimension(570, 180));
        jScrollPaneDisplayArea.setPreferredSize(new java.awt.Dimension(570, 180));

        jTextPaneDisplayArea.setEditable(false);
        jTextPaneDisplayArea.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jTextPaneDisplayArea.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPaneDisplayArea.setViewportView(jTextPaneDisplayArea);

        jScrollPaneInputArea.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPaneInputArea.setMaximumSize(new java.awt.Dimension(450, 50));
        jScrollPaneInputArea.setMinimumSize(new java.awt.Dimension(450, 50));
        jScrollPaneInputArea.setPreferredSize(new java.awt.Dimension(450, 50));

        jTextAreaInput.setColumns(20);
        jTextAreaInput.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jTextAreaInput.setForeground(new java.awt.Color(0, 0, 0));
        jTextAreaInput.setLineWrap(true);
        jTextAreaInput.setRows(5);
        jTextAreaInput.setToolTipText("");
        jScrollPaneInputArea.setViewportView(jTextAreaInput);

        jButtonSend.setBackground(new java.awt.Color(64, 150, 94));
        jButtonSend.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonSend.setForeground(new java.awt.Color(0, 0, 0));
        jButtonSend.setText("Send");
        jButtonSend.setMaximumSize(new java.awt.Dimension(100, 50));
        jButtonSend.setMinimumSize(new java.awt.Dimension(100, 50));
        jButtonSend.setPreferredSize(new java.awt.Dimension(100, 50));
        jButtonSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSendActionPerformed(evt);
            }
        });

        jSliderFuelAmount.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jSliderFuelAmount.setForeground(new java.awt.Color(0, 0, 0));
        jSliderFuelAmount.setMajorTickSpacing(20);
        jSliderFuelAmount.setMinorTickSpacing(10);
        jSliderFuelAmount.setOrientation(javax.swing.JSlider.VERTICAL);
        jSliderFuelAmount.setPaintLabels(true);
        jSliderFuelAmount.setPaintTicks(true);
        jSliderFuelAmount.setMaximumSize(new java.awt.Dimension(100, 540));
        jSliderFuelAmount.setMinimumSize(new java.awt.Dimension(100, 540));
        jSliderFuelAmount.setPreferredSize(new java.awt.Dimension(100, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBoxPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPaneDisplayArea, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabelAreaClearance, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabelSoldierCount, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)
                                    .addComponent(jSpinnerSoldier, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabelAmmoCount, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)
                                    .addComponent(jSpinnerAmmo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(50, 50, 50)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButtonShoot, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonMissile, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonLaser, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jScrollPaneInputArea, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(jButtonSend, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(50, 50, 50)
                .addComponent(jSliderFuelAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jCheckBoxPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonShoot, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAreaClearance, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonMissile, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSoldierCount, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinnerSoldier, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelAmmoCount, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonLaser, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinnerAmmo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPaneDisplayArea, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPaneInputArea, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSend, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jSliderFuelAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(70, 70, 70))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonShootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShootActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonShootActionPerformed

    private void jButtonLaserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLaserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLaserActionPerformed

    private void jButtonMissileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMissileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMissileActionPerformed

    private void jButtonSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSendActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuperDefence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuperDefence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuperDefence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuperDefence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SuperDefence().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLaser;
    private javax.swing.JButton jButtonMissile;
    private javax.swing.JButton jButtonSend;
    private javax.swing.JButton jButtonShoot;
    private javax.swing.JCheckBox jCheckBoxPosition;
    private javax.swing.JLabel jLabelAmmoCount;
    private javax.swing.JLabel jLabelAreaClearance;
    private javax.swing.JLabel jLabelSoldierCount;
    private javax.swing.JScrollPane jScrollPaneDisplayArea;
    private javax.swing.JScrollPane jScrollPaneInputArea;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSlider jSliderFuelAmount;
    private javax.swing.JSpinner jSpinnerAmmo;
    private javax.swing.JSpinner jSpinnerSoldier;
    private javax.swing.JTextArea jTextAreaInput;
    private javax.swing.JTextPane jTextPaneDisplayArea;
    // End of variables declaration//GEN-END:variables
}
